apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
  namespace: elk
spec:
  storageClassName: standard
  volumeName: logstash-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi